### ISSUE TITLE
clips

### ISSUE THREAD

**Issue by jozz024** [offish/twitchtube#26]
it only grabs 5 clips each time i try to run it, and it isn't meeting the time that i want it to be.

**Comment by offish** [comment]
What type of clips are you trying to get? Which channel/game, and period do you have in your config file?

**Comment by jozz024** [comment]
for channel it is _amiibots_ and for period it is "day". if i'm understanding correctly, i assume day means in the same day, could i have a list of all of the period stuff/could you explain it to me if i'm incorrect?

**Comment by offish** [comment]
It probably only grabs 5 clips because there is only 5 clips. If period is set to `day` it will grab the top clips for the last 24 hours. You might want to set it as `week` instead. Here are all the periods you can use: `day`, `week`, `month` and `all`. The language is set to English by default in the `PARAMS`, if the channel is not English, it might only grab a couple or none clips, because it can't find that many English clips.
